ci: drop aix support, add {darwin,windows}/arm64
Follow up/fix for #145.

This is the default promu config in the repo, with the following 2
changes.  With these changes in place, `make crossbuild` succeeds, and
CI should be fixed.

1. Drops aix support, bleve/go-git require things that aren't supported
   on the platform:

    ```
    go: downloading github.com/blevesearch/go-porterstemmer v1.0.3
    go: downloading github.com/mschoch/smat v0.2.0
    # github.com/blevesearch/mmap-go
    /go/pkg/mod/github.com/blevesearch/mmap-go@v1.2.0/mmap.go:77:9: undefined: mmap
    /go/pkg/mod/github.com/blevesearch/mmap-go@v1.2.0/mmap.go:92:11: m.lock undefined (type MMap has no field or method lock, but does have method Lock)
    /go/pkg/mod/github.com/blevesearch/mmap-go@v1.2.0/mmap.go:99:11: m.unlock undefined (type MMap has no field or method unlock, but does have method Unlock)
    /go/pkg/mod/github.com/blevesearch/mmap-go@v1.2.0/mmap.go:104:11: m.flush undefined (type MMap has no field or method flush, but does have method Flush)
    /go/pkg/mod/github.com/blevesearch/mmap-go@v1.2.0/mmap.go:114:11: m.unmap undefined (type *MMap has no field or method unmap, but does have method Unmap)
    # github.com/go-git/go-billy/v5/osfs
    /go/pkg/mod/github.com/go-git/go-billy/v5@v5.9.0/osfs/os_posix.go:17:14: undefined: unix.Flock
    /go/pkg/mod/github.com/go-git/go-billy/v5@v5.9.0/osfs/os_posix.go:24:14: undefined: unix.Flock
    !! command failed: build -o .build/aix-ppc64/prometheus-mcp -ldflags -X github.com/prometheus/common/version.Version=0.18.0 -X github.com/prometheus/common/version.Revision=b17080c5d896a16a4d5a5d80409cf85f025a983c -X github.com/prometheus/common/version.Branch=HEAD -X github.com/prometheus/common/version.BuildUser=root@12fdc5e22f75 -X github.com/prometheus/common/version.BuildDate=20260629-11:06:53  github.com/prometheus/prometheus-mcp/cmd/prometheus-mcp: exit status 1
    make: *** [Makefile.common:236: common-build] Error 1
    !! the base builder docker image exited unexpectedly: exit status 2
    ```

2. Adds support for darwin/arm64 and windows/arm64. This enables support
   for things like apple silicon for newer macs, etc. These build
targets existed previously before the repo was transferred and I know
there are users on these platforms, I'd like to keep them supported if
possible. The setup with promu here produces discrete binaries for each
architecture vs the "fat binaries" that used to be built for darwin with
goreleaser, but I think that's reasonable still.

Signed-off-by: TJ Hoplock <t.hoplock@gmail.com>